### ISSUE TITLE
[PA Review] : UserAuth

### ISSUE THREAD

**Issue by mschl0ss** [mschl0ss/laudable#3]
Lemme know how it looks.  The css is kind of hacky in spots but I've refactored and simplified some of it.  Hopefully you're only looking at the results :).

I have a bug where if I hit back a few times, React breaks.  I've been digging at it for a while and I'm baffled.  Otherwise it should all work.

Feature | Function | Style |
|---|---|---|
| Login | Complete | Complete|
|Signup |  Complete | Complete|
|AuthRoute Splash page |  Complete | Complete|
|ProtectedRoute Splash page |  Complete | Complete|

**Comment by mschl0ss** [comment]
psst check out `/carousel` .

**Comment by evhumphrey** [comment]
Looks great! 

## Some feedback: 

### Sign In Form
- [ ] The warning icon has a checkered background that looks strange
![Screen Shot 2019-07-08 at 11 10 26 AM](https://user-images.githubusercontent.com/6361824/60832606-22e01d00-a171-11e9-9b0d-a39252c4ad11.png)

### Splash
- [ ] The `Click to Try Laudible Free` buttons should have a border radius

**Comment by mschl0ss** [comment]
Fixed warning icon and border radius.
