### ISSUE TITLE
[PA Review]: Categories

### ISSUE THREAD

**Issue by mschl0ss** [mschl0ss/laudable#4]
I ended up doing it a little differently than the MVP.  The MVP didn't have anything about the index, but I did include that.  Also, I'm going to implement real books in 'best sellers' and 'new releases' in the next MVP, which is books.

|Feature|Function|Style|
|---|---|---|
|'Browse' button on NavBar populates with clickable categories from DB| Completed|Completed|
|Index renders parents and their children|Completed|Completed|
|Show renders children if parent, siblings if child (and link to parent)|Completed|Completed|
|Show renders BookSlideShow component renders below categories|Pending|Completed|

**Comment by evhumphrey** [comment]
Looks good 🎉
